name: Deploy Project to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git LFS
        run: git lfs install

      - name: Pull LFS files
        run: git lfs pull

      - name: Install Hugging Face CLI
        run: pip install huggingface_hub

      - name: Push to Hugging Face
        run: |
          # Log in to Hugging Face (replace with your credentials)
          hf login

          # Push all files in the subdirectory to your Hugging Face space
          hf push -u AhmadHashim/Student-Score-Prediction ./Score_Prediction_Based_On_Study_Hours

        env:
          HF_HOME: ${{ github.workspace }}/.cache/huggingface
